accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password-change/', views.PasswordChange.as_view(), name='password_change'),
    path('change-password/done/', views.ChangePasswordDone.as_view(), name='password_change_done'),
]

bestoon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import results_export_pdf

urlpatterns = [
    path('expenses/', include('expenses.urls')),
    path('incomes/', include('incomes.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('settings.urls')),
    path('pdf/', results_export_pdf, name="export_pdf"),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

expenses/urls.py
from django.urls import path
from . import views

app_name = 'expenses'

urlpatterns = [
    path('', views.ExpenseList.as_view(), name='list'),
    path('create/', views.CreateExpense.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateExpense.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteExpense.as_view(), name='delete'),
    path('search/', views.SearchExpense.as_view(), name='search')
]

incomes/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'incomes'

urlpatterns = [
    path('', views.IncomeList.as_view(), name='list'),
    path('create/', views.CreateIncome.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateIncome.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteIncome.as_view(), name='delete'),
    path('search/', views.SearchIncome.as_view(), name='search'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsList.as_view(), name='list'),
    path('<int:pk>/', views.NewsDetail.as_view(), name='detail'),
    path('create/', views.CreateNews.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateNews.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteNews.as_view(), name='delete'),
    path('search/', views.SearchNews.as_view(), name='search')
]

news/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
from tinymce.models import HTMLField


class NewsManager(models.Manager):
    def get_active_news(self):
        return self.get_queryset().filter(is_active=True)

    def search(self, query, user):
        lookup = Q(title__icontains=query)
        if user.is_staff:
            return self.get_queryset().filter(lookup).distinct()
        else:
            return self.get_queryset().filter(lookup, is_active=True).distinct()


class News(models.Model):
    title = models.CharField(max_length=250, verbose_name='عنوان')
    text = models.TextField(verbose_name='متن')
    date = models.DateTimeField(auto_now_add=True, verbose_name='زمان')
    is_active = models.BooleanField(default=False, verbose_name='فعال/غیرغعال')

    objects = NewsManager()

    class Meta:
        verbose_name = 'خبر'
        verbose_name_plural = 'اخبار'

    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

news/views.py
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import News
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .mixins import StaffUserRequired


class NewsList(ListView):
    def get_queryset(self):
        is_staff_user = self.request.user.is_staff
        if is_staff_user:
            return News.objects.all().order_by('-pk')
        return News.objects.get_active_news().order_by('-pk')


class NewsDetail(DetailView):
    def get_queryset(self):
        is_staff_user = self.request.user.is_staff
        if is_staff_user:
            return News.objects.all()
        return News.objects.get_active_news()


class CreateNews(LoginRequiredMixin, StaffUserRequired, CreateView):
    model = News
    fields = '__all__'


class UpdateNews(LoginRequiredMixin, StaffUserRequired, UpdateView):
    model = News
    fields = '__all__'


class DeleteNews(LoginRequiredMixin, StaffUserRequired, DeleteView):
    model = News
    success_url = reverse_lazy('news:list')


class SearchNews(ListView):
    def get_queryset(self):
        request = self.request
        user = self.request.user
        query = request.GET.get('q')

        if query is not None:
            return News.objects.search(query, user)

        return News.objects.get_active_news()

news/templates/news/news_confirm_delete.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}حذف {{ object.title }}{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
    <style>
        input[type="submit"] {
            color: white !important;
        }
    </style>
    <form method="post">
        {% csrf_token %}
            <p>آیا واقعا میخواهید "{{ object.text }}" را حذف کنید ؟</p>
        {{ form }}
        <input type="submit" value="بله" class="btn red white-text waves-effect">
        <a href="{% url 'expenses:list' %}">
            <button type="button" class="btn blue waves-effect">نه</button>
        </a>
    </form>
{% endblock content %}

news/templates/news/news_detail.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %} {{ object.title }} {% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
<ul>
    <li>{{ object.title }}</li>
    <li>{{ object.text }}</li>
    <li>{{ object.date }}</li>
    <li>
        فعال
        {% if object.is_active %}
            است
        {% else %}
            نیست
        {% endif %}
    </li>
</ul>

<a href="{% url 'news:list' %}">لیست اخبار</a>
{% endblock content %}

news/templates/news/news_form.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}ارسال خبر{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|materializecss }}
        <button type="submit" class='btn blue waves-effect'>ارسال خبر</button>
    </form>
{% endblock content %}

news/templates/news/news_list.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}لیست اخبار{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
{% include 'components/search.html' with app_name='news' %}
<ul class="collapsible white black-text amount-text">
    {% for object in object_list %}
    <li>
        <div class="collapsible-header">{{ object.title }}</div>
        <div class="collapsible-body">
            <p>{{ object.text }}</p>
            <br />
            <small>{{ object.date }}</small>
            <br />
            {% if user.is_staff %}
            <div class="action-wrapper">
                <a href=" {% url 'news:update' object.pk %} " class="btn waves-effect blue">ویرایش</a>
                <a href=" {% url 'news:delete' object.pk %} " class="btn waves-effect blue">حذف</a>
            </div>
            {% endif %}
        </div>
    </li>
    {% empty %}
    <p class="err-txt">
        خرجی یافت نشد
    </p>
    {% endfor %}
</ul>

{% if user.is_staff %}
<div class="fixed-action-btn">
    <a class="btn-floating btn-large black plus-btn" href="{% url 'news:create' %}">
        <i class="large fas fa-plus"></i>
    </a>
</div>
{% endif %}
{% endblock content %}