accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password-change/', views.PasswordChange.as_view(), name='password_change'),
    path('change-password/done/', views.ChangePasswordDone.as_view(), name='password_change_done'),
]

bestoon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import results_export_pdf

urlpatterns = [
    path('expenses/', include('expenses.urls')),
    path('incomes/', include('incomes.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('settings.urls')),
    path('pdf/', results_export_pdf, name="export_pdf"),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

expenses/urls.py
from django.urls import path
from . import views

app_name = 'expenses'

urlpatterns = [
    path('', views.ExpenseList.as_view(), name='list'),
    path('create/', views.CreateExpense.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateExpense.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteExpense.as_view(), name='delete'),
    path('search/', views.SearchExpense.as_view(), name='search')
]

incomes/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'incomes'

urlpatterns = [
    path('', views.IncomeList.as_view(), name='list'),
    path('create/', views.CreateIncome.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateIncome.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteIncome.as_view(), name='delete'),
    path('search/', views.SearchIncome.as_view(), name='search'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsList.as_view(), name='list'),
    path('<int:pk>/', views.NewsDetail.as_view(), name='detail'),
    path('create/', views.CreateNews.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateNews.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteNews.as_view(), name='delete'),
    path('search/', views.SearchNews.as_view(), name='search')
]

expenses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Q


class ExpenseManager(models.Manager):
    def get_by_user(self, user):
        return self.get_queryset().filter(user=user)

    def search(self, query, user):
        lookup = Q(text__icontains=query)
        return self.get_queryset().filter(lookup, user=user).distinct()


class Expense(models.Model):
    text = models.CharField(max_length=255, verbose_name='عنوان')
    date = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    amount = models.BigIntegerField(verbose_name='میزان')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='کاربر')

    objects = ExpenseManager()

    class Meta:
        verbose_name = 'خرج'
        verbose_name_plural = 'خرج ها'

    def __str__(self):
        return self.text

expenses/views.py
from bestoon.mixins import UserObjectRequired
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from .models import Expense


class ExpenseList(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Expense.objects.get_by_user(self.request.user).order_by('-pk')




class CreateExpense(LoginRequiredMixin, CreateView):
    model = Expense
    fields = ['text', 'amount']
    success_url = reverse_lazy('expenses:list')

    def form_valid(self, form):
        self.obj = form.save(commit=False)
        self.obj.user = self.request.user
        return super(CreateExpense, self).form_valid(form)


class UpdateExpense(LoginRequiredMixin, UserObjectRequired, UpdateView):
    model = Expense
    fields = ['text', 'amount']


class DeleteExpense(LoginRequiredMixin, UserObjectRequired, DeleteView):
    model = Expense
    success_url = reverse_lazy('expenses:list')


class SearchExpense(ListView):
    def get_queryset(self):
        request = self.request
        user = self.request.user
        query = request.GET.get('q')

        if query is not None:
            return Expense.objects.search(query, user)
        return Expense.objects.get_by_user(user).order_by('-pk')

expenses/templates/expenses/expense_confirm_delete.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}حدف {{ object.text }}{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
<a href="url"></a>
{% endblock navbar_btns %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>آیا واقعا میخواهید شیء زیر را حذف کنید <br> "{{ object.text }}"?</p>
    {{ form }}
    <button type="submit" class="btn red waves-effect">بله</button>
    <a href="{% url 'expenses:list' %}">
        <button type="button" class="btn blue waves-effect">نه</button>
    </a>
</form>
{% endblock content %}

expenses/templates/expenses/expense_detail.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}{{ object.text }}{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
<ul>
    <li>{{ object.text }}</li>
    <li>{{ object.date }}</li>
    <li>{{ object.amount }}</li>
</ul>
<a href="{% url 'expenses:list' %}">لیست خرج ها</a>
{% endblock content %}

expenses/templates/expenses/expense_form.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}اضافه کردن خرج{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
    <h4 class="blue-text center-align  ">اضافه کردن خرج جدید</h4>
    <form method="post">
        {% csrf_token %}
        {{ form|materializecss }}
        <div class="center-align">
            <button type="submit" class='btn btn-large blue waves-effect'>تایید خرج</button>
        </div>
    </form>
{% endblock content %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}لیست خرج ها{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
    {% include 'components/search.html' with app_name='expenses' %}
    <ul class="collapsible white black-text amount-text">
        {% for object in object_list %}
            <li>
                <div class="collapsible-header">{{ object.text }}</div>
                <div class="collapsible-body">
                    <span>{{ object.amount }}</span>
                    <br />
                    <small>{{ object.date }}</small>
                    <br />
                    <div class="action-wrapper">
                        <a href=" {% url 'expenses:update' object.pk %} "
                           class="btn waves-effect blue">ویرایش</a>
                        <a href=" {% url 'expenses:delete' object.pk %} "
                           class="btn waves-effect red">حذف</a>
                    </div>
                </div>
            </li>
        {% empty %}
            <p class="err-txt">
               خرجی یافت نشد
            </p>
        {% endfor %}
    </ul>
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large black plus-btn"
           href="{% url 'expenses:create' %}">
            <i class="large fas fa-plus"></i>
        </a>
    </div>

{% endblock content %}