accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password-change/', views.PasswordChange.as_view(), name='password_change'),
    path('change-password/done/', views.ChangePasswordDone.as_view(), name='password_change_done'),
]

bestoon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import results_export_pdf

urlpatterns = [
    path('expenses/', include('expenses.urls')),
    path('incomes/', include('incomes.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('settings.urls')),
    path('pdf/', results_export_pdf, name="export_pdf"),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

expenses/urls.py
from django.urls import path
from . import views

app_name = 'expenses'

urlpatterns = [
    path('', views.ExpenseList.as_view(), name='list'),
    path('create/', views.CreateExpense.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateExpense.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteExpense.as_view(), name='delete'),
    path('search/', views.SearchExpense.as_view(), name='search')
]

incomes/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'incomes'

urlpatterns = [
    path('', views.IncomeList.as_view(), name='list'),
    path('create/', views.CreateIncome.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateIncome.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteIncome.as_view(), name='delete'),
    path('search/', views.SearchIncome.as_view(), name='search'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsList.as_view(), name='list'),
    path('<int:pk>/', views.NewsDetail.as_view(), name='detail'),
    path('create/', views.CreateNews.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateNews.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteNews.as_view(), name='delete'),
    path('search/', views.SearchNews.as_view(), name='search')
]

templates/base.html
{% load materializecss %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href='{% static "css/materialize/materialize.min.css" %}'
    />
    <script src='{% static "js/materialize/materialize.min.js" %}'></script>

    <link rel="stylesheet" href='{% static "css/fontawsome/all.min.css" %}' />
    <script src='{% static "js/fontawsome/all.min.js" %}'></script>

    <link rel="stylesheet" href="{% static 'css/custom/style.css' %}" />
    <script src="{% static 'js/custom/script.js' %}"></script>

    <title>بستون | {% block title %}{% endblock title %}</title>
    <style>
      @font-face {
        font-family: Estedad;
        src: url("{% static 'fonts/estedad/Estedad.ttf' %}");
      }

      *,
      body {
        font-family: Estedad, "Estedad" !important;
        direction: rtl !important;
        text-align: right !important;
      }
    </style>
  </head>

  <body class="grey darken-3 white-text">
    <header>
      <section class="header navbar-fixed">
        <nav class="grey">
          <div class="nav-wrapper container">
            <a href="/" class="brand-logo">بستون</a>
              {% block bar %}{% endblock bar %}
            <ul class="left hide-on-med-and-down">
              {% block navbar_btns %}{% endblock navbar_btns %}
            </ul>
          </div>
        </nav>
      </section>
    </header>
    <main>
      <div class="container content-section">
        {% block content %}{% endblock content %}
        <div class="hide-on-large-only">
          {% block buttons %}{% endblock buttons %}
        </div>
      </div>
    </main>
    <script>
      var textAreas = document.querySelectorAll('textarea');
      for (textArea of textAreas) {
        textArea.style.color = '#ffffff'
      }
    </script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block content %}
    <div style="text-align:center;">
        <h1>{{ title }}</h1>
        <p>{{ about }}</p>
        <div class="center-align">
            <a class="green btn btn-large waves-effect row" target="_blank" href="{{ github_addr }}">صفحه ی  گیت هاب</a>
            <a class="green btn btn-large waves-effect row" href="{% url 'export_pdf' %}">خروجی PDF دخل و خرج ها تا الان</a>
        </div>
    </div>
    <br>
    <br>
{% endblock content %}
{% block navbar_btns %}
    {% if user %}
        <a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
        <a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
        <a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
        <a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
    {% else %}
        <a href="{% url 'accounts:login' %}" class="btn waves-effect blue">ورود</a>
        <a href="{% url 'accounts:register' %}" class="btn waves-effect blue">ثبت نام</a>
    {% endif %}
{% endblock navbar_btns %}
{% block buttons %}
    {% if user %}
        <div>
            <a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
            <a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
            <a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
            <a href="{% url 'accounts:logout' %}" class="btn waves-effect red">خروج</a>
        </div>
        <br>
        <br>
    {% else %}
        <a href="{% url 'accounts:login' %}" class="btn waves-effect blue">ورود</a>
        <a href="{% url 'accounts:register' %}" class="btn waves-effect blue">ثبت نام</a>
    {% endif %}
{% endblock buttons %}