accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password-change/', views.PasswordChange.as_view(), name='password_change'),
    path('change-password/done/', views.ChangePasswordDone.as_view(), name='password_change_done'),
]

bestoon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import results_export_pdf

urlpatterns = [
    path('expenses/', include('expenses.urls')),
    path('incomes/', include('incomes.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('settings.urls')),
    path('pdf/', results_export_pdf, name="export_pdf"),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

expenses/urls.py
from django.urls import path
from . import views

app_name = 'expenses'

urlpatterns = [
    path('', views.ExpenseList.as_view(), name='list'),
    path('create/', views.CreateExpense.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateExpense.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteExpense.as_view(), name='delete'),
    path('search/', views.SearchExpense.as_view(), name='search')
]

incomes/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'incomes'

urlpatterns = [
    path('', views.IncomeList.as_view(), name='list'),
    path('create/', views.CreateIncome.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateIncome.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteIncome.as_view(), name='delete'),
    path('search/', views.SearchIncome.as_view(), name='search'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsList.as_view(), name='list'),
    path('<int:pk>/', views.NewsDetail.as_view(), name='detail'),
    path('create/', views.CreateNews.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateNews.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteNews.as_view(), name='delete'),
    path('search/', views.SearchNews.as_view(), name='search')
]

incomes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Q


class IncomeManager(models.Manager):
    def get_by_user(self, user):
        return self.get_queryset().filter(user=user)

    def search(self, query, user):
        lookup = Q(text__icontains=query)
        return self.get_queryset().filter(lookup, user=user).distinct()



class Income(models.Model):
    text = models.CharField(max_length=255, verbose_name='عنوان')
    date = models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')
    amount = models.BigIntegerField(verbose_name='میزان')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='کاربر')

    objects = IncomeManager()

    class Meta:
        verbose_name = 'دخل'
        verbose_name_plural = 'دخل ها'

    def __str__(self):
        return self.text

incomes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from bestoon.mixins import UserObjectRequired
from .models import Income


class IncomeList(LoginRequiredMixin, ListView):
    def get_queryset(self):
        """ returns an instance of the model object for every user who visits this page """
        return Income.objects.get_by_user(self.request.user).order_by('-pk')


class CreateIncome(LoginRequiredMixin, CreateView):
    model = Income
    fields = ['text', 'amount']
    success_url = reverse_lazy('incomes:list')

    def form_valid(self, form):
        """called form_valid and the other called create."""
        # set user object
        self.obj = form.save(commit=False)
        self.obj.user = self.request.user
        return super(CreateIncome, self).form_valid(form)


class UpdateIncome(LoginRequiredMixin, UserObjectRequired, UpdateView):
    """
        view uses UserObjectRequired, 
        so it will only update if there is an object with
        the same name as the user's current one on hand
    """
    model = Income
    fields = ['text', 'amount']


class DeleteIncome(LoginRequiredMixin, UserObjectRequired, DeleteView):
    """
    this DeleteView function is called when deleting an income from the database
    """
    model = Income
    success_url = reverse_lazy('incomes:list')


class SearchIncome(ListView):
    def get_queryset(self):
        request = self.request
        user = self.request.user
        query = request.GET.get('q')  # find search query

        # check query
        if query is not None:
            return Income.objects.search(query, user)

        # return income list if query is none
        return Income.objects.get_by_user(user).order_by('-pk')

incomes/templates/incomes/income_confirm_delete.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}حذف {{ object.text }}{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>آیا واقعا میخواهید شیء زیر را حذف کنید <br> "{{ object.text }}"?</p>
    {{ form }}
    <input type="submit" value="بله" class="btn waves-effect red">
    <a href="{% url 'expenses:list' %}">
        <button type="button" class="btn waves-effect blue">نه</button>
    </a>
</form>
{% endblock content %}

incomes/templates/incomes/income_detail.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}{{ object.text }}{% endblock title %}
{% block navbar_btns %}
    <a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
    <a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
    <a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
    <a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
    <ul>
        <li>{{ object.text }}</li>
        <li>{{ object.date }}</li>
        <li>{{ object.amount }}</li>
    </ul>
    <a href="{% url 'incomes:list' %}">لیست دخل ها</a>
{% endblock content %}

incomes/templates/incomes/income_form.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}اضافه کردن دخل جدید{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div style="center-align">	
    	<button type="submit" class="btn btn-large waves-effect blue">تایید دخل</button>
    </div>
</form>
{% endblock content %}

incomes/templates/incomes/income_list.html
{% extends "base.html" %}
{% load materializecss %}
{% block title %}لیست دخل ها{% endblock title %}
{% block navbar_btns %}
<a class="btn waves-effect blue" href="{% url 'expenses:list' %}">خرج ها</a>
<a class="btn waves-effect blue" href="{% url 'incomes:list' %}">دخل ها</a>
<a class="btn waves-effect blue" href="{% url 'news:list' %}">اخبار</a>
<a href="{% url 'accounts:logout' %}" class="btn waves-effect blue">خروج</a>
{% endblock navbar_btns %}
{% block content %}
{% include 'components/search.html' with app_name='incomes' %}
<ul class="collapsible white black-text amount-text">
    {% for object in object_list %}
        <li>
            <div class="collapsible-header">{{ object.text }}</div>
            <div class="collapsible-body">
                <span>
                    {{ object.amount }}
                </span>

                <br>

                <small>
                    {{ object.date }}
                </small>

                <br>
                
                <div class="action-wrapper">
                    <a href="{% url 'incomes:update' object.pk %}" class="btn waves-effect blue">ویرایش</a>
                    <a href="{% url 'incomes:delete' object.pk %}" class="btn waves-effect red">حذف</a>
                </div>
            </div>
        </li>
    {% empty %}
        <p class="err-txt">
           دخلی یافت نشد
        </p>
    {% endfor %}
</ul>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large black plus-btn" href="{% url 'incomes:create' %}">
        <i class="large fas fa-plus"></i>
    </a>
</div>
{% endblock content %}